### PR TITLE
Travis CI notification to Slack

### PR DESCRIPTION
**Pull request by shashankitmaster**
Added CI notification to slack. 

Please review so that I can merge to `release` branch

---
This change is [Reviewable](https://reviewable.io/reviews/yugandhargangu/bettle-track/15)

### CODE REVIEW

**Comment by shashankitmaster** [comment]
image

Please check the result after addition of this in `.travis.yml`

**Review by yugandhargangu — APPROVED** [review]

**Comment by shashankitmaster** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/yugandhargangu/bettle-track/15)*

**Comment by shashankitmaster** [comment]
Hello all thanks for approval. I am merging into `release`.

**Comment by yugandhargangu** [comment]
OK

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/yugandhargangu/bettle-track/15#-:-KgSorvY3mi3miw_RUKf:b2nhksp)*

**Pull request merged**
