### PR TITLE
Database design

### PR DESCRIPTION
**Pull request by yugandhargangu**
Updated database document

### CODE REVIEW

**Comment by shashankitmaster** [comment]
@yugandhargangu : Try to update the documents in same pull request. 

I think you closed previous pull request.

**Comment by yugandhargangu** [comment]
Yes. I closed it. Am I need to reopen it??

**Comment by shashankitmaster** [comment]
@yugandhargangu : No need to reopen now. Better try to do it from next time.

**Comment by yugandhargangu** [comment]
Okay

**Review by shashankitmaster — CHANGES_REQUESTED** [review]
Java Enum: `IssueState` 

Add one more state : `REVIEW`

**Comment by yugandhargangu** [comment]
May I know what is the state REVIEW means??

**Comment by shashankitmaster** [comment]
@yugandhargangu : I want to add that state when some project manager or team members are checking that bug has been really resolved or not. So at that time the issue goes into that state.

**Comment by yugandhargangu** [comment]
But we have RESOLVED state for that right?
What's difference between RESOLVED and REVIEW??

**Comment by shashankitmaster** [comment]
@yugandhargangu : RESOLVED means that issue has been RESOLVED by assignee and has gone under review also.  Otherwise do one thing make two state of RESOLVED - actual RESOLVED and REVIEW REQUEST.

**Review by shashankitmaster — APPROVED** [review]
Please merge this changes to master

**Pull request merged**
