### PR TITLE
Database design document update

### PR DESCRIPTION
**Pull request by yugandhargangu**
Updated database design document according to new prototype

### CODE REVIEW

**Comment by ranjeet1515** [comment]
Document Added

**Comment by shashankitmaster** [comment]
I think it will be good if we add a table to keep track of resolution of any issues. 
So we can get a good workflow.

**Comment by yugandhargangu** [comment]
Actually we have a history table, which contains all the track history including resolutions.

**Review by shashankitmaster — COMMENTED** [review]
Do we have any plans for adding approvers, reviewers and watchers to issues.

**Review by shashankitmaster — COMMENTED** [review]
Please change the Java type of `Date` to `LocalDate` or `LocalDateTime(in case of timestamp at DB level)` as we are planning to use `Java 8`

**Review by shashankitmaster — CHANGES_REQUESTED** [review]
What about adding `login_retry_count` as a field for user, so that we can have a count of login retries by the user.

**Review by shashankitmaster — COMMENTED** [review]
Please elaborate the use of `m_modules` , `m_users_modules`. Because I can't see any module wise differentiate in Projects.

**Comment by yugandhargangu** [comment]
m_projects table contains project information.
m_modules table contains module information.
Some projects may contain multiple modules. Every project may not contain modules. 

So m_project_users table contains accessible members at project level documents, test cases and issues.

m_module_users table contains accessible members at module level documents, test cases and issues.

Table columns looks same but the usage is different.

**Pull request closed without merging**
